apiVersion: kudo.dev/v1beta1
kind: Operator
metadata:
  creationTimestamp: "2021-08-01T13:52:44Z"
  generation: 1
  managedFields:
  - apiVersion: kudo.dev/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:kubernetesVersion: {}
        f:maintainers: {}
        f:url: {}
      f:status: {}
    manager: kubectl-kudo
    operation: Update
    time: "2021-08-01T13:52:44Z"
  name: first-operator
  namespace: default
  resourceVersion: "6437"
  uid: 1e514b15-4b05-45b0-bca9-022e600e0e96
spec:
  kubernetesVersion: 1.13.0
  maintainers:
  - email: <your@email.com>
    name: Your name
  url: https://kudo.dev
status: {}
