apiVersion: v1
items:
- metadata:
    creationTimestamp: "2021-08-01T13:23:56Z"
    labels:
      app: kudo-manager
      control-plane: controller-manager
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
            f:control-plane: {}
        f:spec:
          f:ports:
            .: {}
            k:{"port":443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
            f:control-plane: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-kudo
      operation: Update
      time: "2021-08-01T13:23:56Z"
    name: kudo-controller-manager-service
    namespace: kudo-system
    resourceVersion: "3127"
    uid: 53950216-f377-426f-afb3-48895cc12691
  spec:
    clusterIP: 10.96.236.141
    ports:
    - name: kudo
      port: 443
      protocol: TCP
      targetPort: webhook-server
    selector:
      app: kudo-manager
      control-plane: controller-manager
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "11010"
