apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  selector:
    matchLabels:
      app: hello-busybox
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-busybox
    spec:
      containers:
      - name: hello
        image: busybox 
        command: ["echo", "Hello, {{ .Values.myname }}"]
