#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: nginx-deployment
#spec:
#  selector:
#    matchLabels:
#      app: nginx
#  replicas: {{ .Params.replicas }} # tells deployment to run 2 pods matching the template
#  template:
#    metadata:
#      labels:
#        app: nginx
#    spec:
#      containers:
#        - name: nginx
#          image: nginx:{{ .AppVersion }}
#          ports:
#            - containerPort: 80
#
#
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Params.podname }} # Sets the pod name 
spec:
  restartPolicy: OnFailure
  containers:
  - name: hello
    image: busybox
    command: ["echo", "Hello, %s!" {{ .Params.myname }}] # Sets my name

